### PR TITLE
Manual smartapi_sync error handling

### LINKED ISSUE #478: Manual smartapi_sync error handling
Currently, if an error is caught during automated syncing of SmartAPI, the failure is logged and BTE moves on. During manual syncing such as `npm run smartapi_sync`, however, an error in the initial request causes the process to crash with a less-than-informative error. This error should be caught and logged similarly to the automated run.

Additionally, if both`API_OVERRIDE` and `only_overrides` are true, the initial request should be skipped so that cases where only override APIs are being tested work regardless of the status of SmartAPI's server.

All code related to this issue is in [this file](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/controllers/cron/update_local_smartapi.js).

### PR DESCRIPTION
**Pull request by mnarayan1**
Meant to fix [this issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/478). I'm not sure if I tackled the second part of the issue correctly (skip initial request if both `API_OVERRIDE `and `only_overrides` are true), so let me know if there is anything I should fix.

### CODE REVIEW

**Comment by rjawesome** [comment]
Note (you could wait for someone else to confirm or just test it yourself), in line 244 you are using a try/catch on a promise. try/catch only works on synchronous code (unless async/await is used) and hence errors in promises won't be caught. [Stackoverflow Post about this](https://stackoverflow.com/questions/24977516/catching-errors-in-javascript-promises-with-a-first-level-try-catch)<br> Your code: 

```javascript
try {
  updateSmartAPISpecs().then(() => {
      console.log("SmartAPI sync successful.");
      process.exit(0);
  });
} catch (err) {
  debug(`Updating local copy of SmartAPI specs failed! The error message is ${err.toString()}`)
}
        
```

* updateSmartAPISpecs returns a promise because it is an async function

Promises have a .catch function which can be used like so:
```javascript
promise.then(() => console.log("success")).catch(err => console.error(err.toString()))
//or in this example
updateSmartApiSpecs().then(() => code).catch(err => code)
```

I'd also recommend testing your code (if you haven't already) by running the smartapi_sync (npm run smartapi_sync) with different environment variables, and to test error handling you could manually add an error in the code like so:
```
throw new Error("err")
```

**Comment by mnarayan1** [comment]
Thanks for catching that! That issue should be fixed now.

**Comment by tokebe** [comment]
The first part of the issue is resolved correctly. I should have been more clear on the second part: 

If [this request](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/280226981c25f1a072b6c8c3002a8fc0372478f5/src/controllers/cron/update_local_smartapi.js#L156) fails, and `API_OVERRIDE` and `only_overrides` are both true, then the failure should be ignored, and the rest of the function should proceed as normal. See `getAPIOverrides()` in the same file for accessing `only_overrides` -- it's fine to refactor the code to read `smartapi_overrides.json` prior to the `getAPIOverrides()` call and pass it in if that simplifies anything.

File: src/controllers/cron/update_local_smartapi.js [hunk 1]
```diff
@@ -153,7 +153,19 @@ const getOpsFromPredicatesEndpoints = async (specs) => {
...
+    const overridesPath = path.resolve(__dirname, "../config/smartapi_overrides.json");
+    let overrides;
+    try {
+        overrides = JSON.parse((await readFile(overridesPath)));
+    } catch (error) {
+        debug(`ERROR getting API Overrides file because ${error}`);
+        return;
+    }
+    const res = await axios.get(SMARTAPI_URL, { headers: { 'User-Agent': userAgent } }).catch((err) => {
+        if(!(process.env.API_OVERRIDE === "true" && overrides)) {
```
Comment (tokebe) [inline src/controllers/cron/update_local_smartapi.js]: This error should be logged if API_OVERRIDE and overrides exist, rather than if they don't.

Comment (tokebe) [reply src/controllers/cron/update_local_smartapi.js]: `res` should have the structure used by the rest of this function (and `getAPIOverrides`) re-created if the request fails, so that overrides can be created properly.

File: src/controllers/cron/update_local_smartapi.js [hunk 2]
```diff
@@ -153,7 +153,19 @@ const getOpsFromPredicatesEndpoints = async (specs) => {
 
 const updateSmartAPISpecs = async () => {
     const SMARTAPI_URL = 'https://smart-api.info/api/query?q=tags.name:translator&size=1000&sort=_seq_no&raw=1&fields=paths,servers,tags,components.x-bte*,info,_meta';
-    const res = await axios.get(SMARTAPI_URL, { headers: { 'User-Agent': userAgent } });
+    const overridesPath = path.resolve(__dirname, "../config/smartapi_overrides.json");
```
Comment (tokebe) [inline src/controllers/cron/update_local_smartapi.js]: Currently syncing fails because this path is invalid. It should be `../../config/smartapi_overrides.json`. 

I'd recommend testing this PR using the `Sync SmartAPI` and `Sync SmartAPI (with overrides)` vscode debugging launchers, and intentionally breaking the request URL (taking out the ".info" should be sufficient) to test behavior on failed requests.

File: src/controllers/cron/update_local_smartapi.js [hunk 3]
```diff
@@ -269,25 +283,28 @@ module.exports = () => {
...
+        const overridesPath = path.resolve(__dirname, "../../config/smartapi_overrides.json");
+        let overrides
+        try {
+            overrides = JSON.parse(fs.readFileSync(overridesPath));
+        } catch (error) {
+            debug(`ERROR getting API Overrides file because ${error}`);
+            return;
+        }
+
+        if(!(api_override && overrides.conf.only_overrides)) {
```
Comment (tokebe) [inline src/controllers/cron/update_local_smartapi.js]: This would appear to schedule the cron job only if overrides are not set. The cron job should be scheduled so long as `disable_smartapi_sync` is `false`

File: src/controllers/cron/update_local_smartapi.js [hunk 4]
```diff
@@ -269,25 +283,28 @@ module.exports = () => {
...
+                    await updateSmartAPISpecs();
+                    debug("Successfully updated the local copy of SmartAPI specs.")
+                } catch (err) {
+                    debug(`Updating local copy of SmartAPI specs failed! The error message is ${err.toString()}`)
+                }
+            });
+        }
 
         if (api_override) {
-            const overridesPath = path.resolve(__dirname, "../../config/smartapi_overrides.json");
```
Comment (tokebe) [inline src/controllers/cron/update_local_smartapi.js]: I don't see the reason to move this part of the code, as the area of concern is in the above `updateSmartAPISpecs()` function.

File: src/controllers/cron/update_local_smartapi.js [hunk 5]
```diff
@@ -244,6 +256,8 @@ module.exports = () => {
         updateSmartAPISpecs().then(() => {
             console.log("SmartAPI sync successful.");
             process.exit(0);
+        }).catch(err => {
```
Comment (tokebe) [inline src/controllers/cron/update_local_smartapi.js]: This catches failures correctly 👍

**Review by tokebe — CHANGES_REQUESTED** [review]
There are still a few issues with this PR that need to be addressed. I've added some comments to this review to point out the specific areas and the expected behavior.

File: src/controllers/cron/update_local_smartapi.js (hunk 1 above)
Comment (mnarayan1) [reply src/controllers/cron/update_local_smartapi.js]: Hm, I think I misunderstood you about this. Do you mean that if `API_OVERRIDE` and `overrides` exist, the error is logged, and overrides are created with the local file instead? And, if `API_OVERRIDE` and `overrides` don't exist, the error is thrown?

Comment (tokebe) [reply src/controllers/cron/update_local_smartapi.js]: If `API_OVERRIDE` is `true` and the [config `only_overrides`](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/6b6d07106b8c04aeca3723a1d5c9a7dce0b9fd74/src/config/smartapi_overrides.json#L3) is also `true`, when the initial smartAPI request fails, we should see an error saying it failed, and it should proceed to create the smartAPI specs from only what's provided by the overrides config.

If both of those are not true, then the error should be logged to explain why updating smartAPI specs failed entirely.

File: src/controllers/cron/update_local_smartapi.js [hunk 6]
```diff
@@ -153,24 +153,68 @@ const getOpsFromPredicatesEndpoints = async (specs) => {
...
+                    date_created: undefined,
+                    last_updated: undefined,
+                    url: overrides.apis[id],
+                    username: undefined,
+                };
+                hits.push(override)
+                fs.writeFile(localFilePath, JSON.stringify({ hits: hits }), (err) => {
+                    if (err) throw err;
+                })
+            });
```
Comment (tokebe) [inline src/controllers/cron/update_local_smartapi.js]: You don't have to duplicate the functionality of `getAPIOverrides()` (which has more functionality that what you've added here). You can instead just create a mock `res.data` object containing an empty array `hits` and call `getAPIOverrides()` on it, letting the existing function handle override creation. Then you can pass those hits to the rest of the function.

This mocked `res.data` could be created prior to the request and overwritten with the actual `res.data` using your condition `if (await res) {}`.

File: src/controllers/cron/update_local_smartapi.js [hunk 7]
```diff
@@ -153,24 +153,68 @@ const getOpsFromPredicatesEndpoints = async (specs) => {
...
+        //clean _score fields
+        const hits = res.data.hits;
+        hits.forEach(function(obj){ delete obj._score });
+        writeFunc(localFilePath, JSON.stringify({ hits: hits }), (err) => {
+            if (err) throw err;
+        });
+        const predicatesInfo = await getOpsFromPredicatesEndpoints(res.data.hits);
+        writeFunc(predicatesFilePath, JSON.stringify(predicatesInfo), (err) => {
+            if (err) throw err;
+        });
```
Comment (tokebe) [inline src/controllers/cron/update_local_smartapi.js]: Predicates have to be generated whether the initial smartAPI request succeeds or not -- these are generated using the hits that are acquired from the request and/or from overrides.

**Review by tokebe — CHANGES_REQUESTED** [review]
Getting there, just a few more notes on intended behavior.

**Review by tokebe — APPROVED** [review]
